config/routes.rb
Rails.application.routes.draw do
  get "/", to: "links#index", as: :root

  get "/signup", to: "users#new", as: :new_user
  post "/users", to: "users#create"

  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: :logout

  post "/links", to: "links#create"

  get "/links/:id", to: "links#edit", as: :edit_link
  patch "/links/:id", to: "links#update"

  patch "/api/v1/reads", to: "api/v1/reads#create", as: :mark_read
  patch "/api/v1/unreads", to: "api/v1/unreads#create", as: :mark_unread
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :url, url: true, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, uniqueness: true, presence: true

  has_many :links
end

app/controllers/api/v1/reads_controller.rb
class Api::V1::ReadsController < ApiController
  def create
    link = Link.find(params[:id])
    link.update(read: true)
    respond_with status: 200
  end
end

app/controllers/api/v1/unreads_controller.rb
class Api::V1::UnreadsController < ApiController
  def create
    link = Link.find(params[:id])
    link.update(read: false)
    respond_with status: 200
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  respond_to :json
  protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    if current_user
      @links = current_user.links.order('created_at DESC')
    else
      redirect_to login_path
    end
  end

  def create
    link = Link.new(link_params)
    link.user = current_user
    if link.save
      flash[:notice] = "link added!"
      redirect_to root_path
    else
      flash[:error] = "invalid link"
      redirect_to root_path
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    link = Link.find(params[:id])
    if link.update_attributes(link_params)
      flash[:notice] = "link edited!"
      redirect_to root_path
    else
      flash[:error] = "invalid link"
      redirect_to root_path
    end
  end

private

  def link_params
    params.permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "logged in!"
      redirect_to '/'
    else
      flash[:error] = "invalid login"
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "signed up!"
      redirect_to '/'
    else
      flash[:error] = "invalid sign up"
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThoughtBox</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if current_user %>
      <%= link_to "log out", logout_path %>
    <% else %>
      <%= link_to "log in", login_path %>
      <span>  </span>
      <%= link_to "sign up", new_user_path %>
    <% end %>

    <% flash.each do |f| %>
      <p><%= f[1] %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/links/edit.html.erb
<h2>edit link</h2>

<%= form_for(@link, url: "/links/#{@link.id}") do %>
  Title: <%= text_field_tag :title, @link.title %>
  URL: <%= text_field_tag :url, @link.url %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/links/index.html.erb
<h1>ThoughtBox</h1>

<%= form_tag '/links' do %>
  Title: <%= text_field_tag :title %>
  URL: <%= text_field_tag :url %>
  <%= submit_tag "Submit" %>
<% end %>

<br>
<div>
  <span class="search">
    <label>Search: </label>
    <%= text_field :link, :search %>
  </span>

  <span>
  Filter by Status:
  <select class="filter">
    <option value="all">All</option>
    <option value="true">Read</option>
    <option value="false">Unread</option>
  </select>
  </span>

  <span>
    <button id="alphabetic-filter">Filter Alphatically</button>
  </span>
</div>

<ul class="links">
  <% @links.each do |l| %>
    <div id="<%= l.id %>" class="link">
      <% if l.read %>
        <li><a class="read title" href="<%= l.url %>"><%= l.title %></a></li>
        <li class="status">Read: <%= l.read %></li>
        <button class="mark-unread" data-id="<%= l.id %>">mark unread</button>
      <% else %>
        <li><a class="unread title" href="<%= l.url %>"><%= l.title %></a></li>
        <li class="status">Read: <%= l.read %></li>
        <button class="mark-read" data-id="<%= l.id %>" >mark read</button>
      <% end %>
      <%= link_to "edit", edit_link_path(l.id) %>
    </div>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>Signup</h2>

<%= form_for @user do |f| %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>

  <%= f.submit "Submit" %>
<% end %>